### ISSUE TITLE
bud not building again...

### ISSUE THREAD

**Issue by phillipp** [indutny/bud#101]
I still don't understand why the bud build process is so fragile and complicated. Doesn't compile, again:

Checked out the repo @ /tmp/bud, changed to the dir and trying to compile from source:

```
 ~ npm install
npm WARN lifecycle bud@4.0.27~install: cannot run in wd %s %s (wd=%s) bud@4.0.27 gypkg build bud.gyp.json --insecure /tmp/bud
```

Then:
```
~ gypkg build
-bash: /usr/bin/gypkg: No such file or directory
```

So then I tried the one from node_modules only tro get another error message:

```
[...]
CC obj/gypkg_deps/gypkg/openssl@semver-56b1cd0/openssl/crypto/bn/asm/openssl.x86_64-gcc.o
CC obj/gypkg_deps/gypkg/openssl@semver-56b1cd0/openssl/crypto/bf/openssl.bf_enc.o
CC obj/gypkg_deps/gypkg/openssl@semver-56b1cd0/openssl/crypto/bn/openssl.rsaz_exp.o
CC obj/gypkg_deps/gypkg/openssl@semver-56b1cd0/openssl/crypto/cast/openssl.c_enc.o
CC obj/gypkg_deps/gypkg/openssl@semver-56b1cd0/openssl/crypto/camellia/openssl.cmll_misc.o
CC obj/gypkg_deps/gypkg/openssl@semver-56b1cd0/openssl/crypto/des/openssl.des_enc.o
CC obj/gypkg_deps/gypkg/openssl@semver-56b1cd0/openssl/crypto/des/openssl.fcrypt_b.o
CC obj/gypkg_deps/gypkg/openssl@semver-56b1cd0/openssl/crypto/ec/openssl.ecp_nistz256.o
CC obj/gypkg_deps/gypkg/openssl@semver-56b1cd0/openssl/crypto/ui/openssl.ui_compat.o
CC obj/deps/parson/parson/parson.parson.o
ALINK libringbuffer.a
ALINK libuv.a
ALINK libhttp_parser.a
----- STDOUT -----

----- STDERR -----
gcc: error: ../../deps/parson/parson/parson.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.

/tmp/bud/node_modules/gypkg/node_modules/gyp.js/lib/gyp/generator/ninja/index.js:764
        throw err;
        ^

Error: Command failed: /bin/sh -c gcc -MMD -MF obj/deps/parson/parson/parson.parson.o.d -DNDEBUG  -Wno-unused-function -m64 -g  -c ../../deps/parson/parson/parson.c -o obj/deps/parson/parson/parson.parson.o
gcc: error: ../../deps/parson/parson/parson.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:854:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
/tmp/bud/node_modules/gypkg/bin/gypkg:70
      throw err;
      ^

Error: GYP failure
    at ChildProcess.<anonymous> (/tmp/bud/node_modules/gypkg/lib/gypkg/server.js:204:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
```

Node is v4.7.3

What is the problem?

It works just fine on some other ubuntu trusty system. I have no clue what the difference between the systems is.

**Comment by phillipp** [comment]
Okay, that was dumb. Need to checkout the submodules, too. Will think next time before opening an issue...

**Comment by indutny** [comment]
No problem
