### ISSUE TITLE
"gypkg build" encounter error

### ISSUE THREAD

**Issue by luckypoem** [indutny/bud#109]
hi.
on my linux vps,

npm install -g gypkg
git clone https://github.com/indutny/bud
cd bud
npm install
gypkg build

it shows:
...
Call to 'gypkg deps "git://github.com/libuv/libuv.git@^1.9.0 => uv.gyp:libuv" "git://github.com/nodejs/http-parser@^2.7.1 [gpg] => http_parser.gyp:http_parser" "git://github.com/gypkg/ringbuffer@^1.0.0 [gpg] => ringbuffer.gyp:ringbuffer" "git://github.com/gypkg/openssl@~1.2.10 [gpg] => openssl.gyp:openssl" failed while in /root/bud/bud.gyp
while trying to load /root/bud/bud.gyp
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:648:13)
    at Input.execSync (/root/node-v10.14.1-linux-x64/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:80:23)
    at _loop (/root/node-v10.14.1-linux-x64/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:691:26)
    at Input.expandVariables (/root/node-v10.14.1-linux-x64/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:781:5)
    at Input.processVariablesAndConditionsInList (/root/node-v10.14.1-linux-x64/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:1119:27)
    at /root/node-v10.14.1-linux-x64/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:1095:14
    at Array.forEach (<anonymous>)
    at Input.processVariablesAndConditionsInDict (/root/node-v10.14.1-linux-x64/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:1084:24)
    at Input.processVariablesAndConditionsInList (/root/node-v10.14.1-linux-x64/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:1117:12)
/root/node-v10.14.1-linux-x64/lib/node_modules/gypkg/bin/gypkg:70
      throw err;
      ^

Error: GYP failure
    at ChildProcess.proc.on (/root/node-v10.14.1-linux-x64/lib/node_modules/gypkg/lib/gypkg/server.js:204:23)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
root@wh:~/bud#

how to fix it?
tks a lot

**Comment by indutny** [comment]
Tbh, I haven't updated this project in a very long time. It might be unsafe to use it!
