### ISSUE TITLE
Another segfault with SNI

### ISSUE THREAD

**Issue by phillipp** [indutny/bud#96]
Hey,
I was cleaning up the old core dumps and noticed that I got a new one. Seems to stem from the SNI code again, but an extremely rare one (took about one week to occur just once):

```
#0  __GI___libc_free (mem=0x2020202020202020) at malloc.c:2929
        ar_ptr = <optimized out>
        p = <optimized out>
        hook = 0x0
#1  0x00000000005c5732 in bud_sni_from_json (config=0x1f33040, json=0x854e3930, ctx=0x854cfe00) at ../../src/sni.c:107
        obj = 0x8557deb0
        val = 0x0
        cert_str = 0x0
        key_str = 0x0
        pass_str = 0x0
        cert_strs = 0x0
        key_strs = 0x0
        pass_strs = 0x0
        err = {code = kBudErrJSONParse, data = {str = 0x66b826 "<SNI Response>", ret = 6731814}}
#2  0x00000000005b0bc6 in bud_client_sni_cb (req=0x807702c0, err=...) at ../../src/client.c:505
        client = 0x854bfe30
        config = 0x1f33040
        cerr = {err = {code = 2236496176, data = {str = 0x8544ff00 "\001", ret = -2059075840}}, side = 0x8557deb0}
        r = 0
        chain = 0x2
        ctx = 0x5e5955 <parse_object_value+775>
        x509 = 0x0
        pkey = 0x7fffac0798d8
#3  0x00000000005c0830 in bud_http_request_done (request=0x807702c0) at ../../src/http-pool.c:292
No locals.
#4  0x00000000005c1300 in bud_http_request_read_cb (stream=0x807702e0, nread=95, buf=0x7fffac079990) at ../../src/http-pool.c:553
        req = 0x807702c0
        parsed = 95
        out = 0x852d4f40 ""
        len = 24
#5  0x00000000005d6795 in uv__read (stream=0x807702e0) at ../../gypkg_deps/libuv/libuv.git@semver-8fc724d/src/unix/stream.c:1197
        buflen = 8096
        buf = {
          base = 0x807704f8 "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 24\r\n\r\n{\"cert\":null,\"key\":null}RTIFICATE-----\\n******REDACTED********"..., len = 8096}
        nread = 95
        msg = {msg_name = 0x85592920, msg_namelen = 2886179360, msg_iov = 0x1f41890, msg_iovlen = 4213248, msg_control = 0x7fffac079a40, msg_controllen = 5966232, msg_flags = 32774288}
        cmsg_space = "\024\000\000\000\000\000\000\000\001\000\000\000\001", '\000' <repeats 19 times>, " )Y\205\000\000\000\000\000\316\356\064\261\000\312\341p\251X\205\000\000\000\000p\232\a\254\377\177", '\000' <repeats 18 times>, " )Y\205", '\000' <repeats 12 times>, "\340\232\a\254\377\177\000\000\263\356Z\000\000\000\000\000\210!˄\000\000\000\000\b!˄\001\000\000\000\270\263O\205\000\000\000\000\060\263O\205", '\000' <repeats 20 times>, " )Y\205\000\000\000\000\220P\032\205\000\000\000\000\222\020\\\000\000\000\000\000\250\250Y\205\000\000\000\000\340\232\a\254\377\177\000\000p\251"...
        count = 31
        err = 2
        is_ipc = 0
#6  0x00000000005d695b in uv__stream_io (loop=0x8caaa0 <default_loop_struct>, w=0x80770368, events=1) at ../../gypkg_deps/libuv/libuv.git@semver-8fc724d/src/unix/stream.c:1264
        stream = 0x807702e0
```

It's only a hunch, but I think the `free` in question might already be free'd in bud_context_free or not even initalized.

The core dump is 2 gigabytes. Should I upload it for you?

**Comment by indutny** [comment]
Should be fixed now, thank you!
